### PR TITLE
adds landing page

### LINKED ISSUE #54: Landing Page
Implement the landing page (see [hi-fi](https://www.figma.com/file/JjYgK3Y4ft9etm31mPczVW/hi-fi-linux)). 

Also add some slow falling snow animation (you might want to use something like Snow.js or particles.js)

### PR DESCRIPTION
**Pull request by snigdha-kansal**
feat: add landing page and start button

## Summary

Closes #54 

-created landing.svg for landing page
-created startButton.scss for start button on landing page
-created landing.tsx for landing page
-edited globalTypes.ts to include landing page in hamburger menu

## Test Plan

ran yarn start
also ran yarn lint to check for formatting
image:
image

### CODE REVIEW

**Comment by snigdha-kansal** [comment]
the start button does not move as expected when i custom size the chrome window, is there a way i can fix that?
i tried using vw and % for the dimensions but that did not help much
image:
image

**Review by archishadatta — CHANGES_REQUESTED** [review]
Make the iceberg portion a separate HTML component , like we talked about during the meeting, and use CSS positioning to place it on the bottom left.

**Comment by jason2020** [comment]
Hi, I made some fixes for the header to make it work with the landing page. #79  Sorry about that, I didn't think about there being a landing page where the nav bar doesn't show. It just makes it so you don't have to write out `<Header/>` for each component. Feel free to use these changes or keep it as it is now.

**Comment by snigdha-kansal** [comment]
Hi, no worries, I merged your changes to the branch. Thank you!

**Review by archishadatta — APPROVED** [review]

**Pull request merged**
