### PR TITLE
Documentation and QA

### PR DESCRIPTION
**Pull request by bliutech**
Did some review of the existing content and some documentation updates. Reviewed pages "Intro" to "Creation and Deletion". Documentation still needs to be slimmed down and also the rest of the pages need some content fixes as well so this is left open to slowly fix those.

### CODE REVIEW

**Comment by bliutech** [comment]
@zhangjuliet thoughts on moving the ending page Tux to its own page? I think it would be nice to have the permissions content on its own page and have the ending page be by itself. I could also quickly put together a progress check as well? (show a ratio of how many completed tasks ex. 10/21)

image

**Comment by bliutech** [comment]
The "Creation and Deletion" page is now getting a bit cluttered and it feels like its missing some of the "Examples" like some of the other sections before the task itself. Maybe it's worth splitting up into a "Creation" page, a "Deletion" page, and a "Moving and Copying" page? I see #175 but might be a bit tricky to do subpages as opposed to its own pages.

**Comment by bliutech** [comment]
The "Piping" page might be worth renaming to "Input and Output (I/O)" and this transitions nicely into "I/O Redirection". I also realized that we don't have a task that uses the "|" operator. Maybe we should create one on its own page and call it "Piping" instead.

**Comment by bliutech** [comment]
> @zhangjuliet thoughts on moving the ending page Tux to its own page? I think it would be nice to have the permissions content on its own page and have the ending page be by itself. I could also quickly put together a progress check as well? (show a ratio of how many completed tasks ex. 10/21)
> 
> image

Another idea similar to this is to also provide a page where there's just a terminal for them to play with afterwards. Similar to PicoGym's web terminal. Probably leave a note on there somewhere that our terminal is very limited lol.

**Comment by bliutech** [comment]
@zhangjuliet Let's try to merge this for now so that we can consolidate all of our changes.

**Comment by zhangjuliet** [comment]
> @zhangjuliet thoughts on moving the ending page Tux to its own page? I think it would be nice to have the permissions content on its own page and have the ending page be by itself. I could also quickly put together a progress check as well? (show a ratio of how many completed tasks ex. 10/21)

I'm not entirely sure we need a separate page, but let me think about that for a minute.
I like the idea of a progress check though! Would that be a stat that appears on every page and updates as the user goes along, or just a summary stat at the very end? If it's the latter, a separate Ending page would be reasonable, otherwise I'm not sure we need another page.

<hr>

> The "Creation and Deletion" page is now getting a bit cluttered and it feels like its missing some of the "Examples" like some of the other sections before the task itself. Maybe it's worth splitting up into a "Creation" page, a "Deletion" page, and a "Moving and Copying" page? I see https://github.com/uclaacm/linux-lab/pull/175 but might be a bit tricky to do subpages as opposed to its own pages.

Did you have any examples in mind?
Yeah, I agree that splitting into the three pages might reduce clutter, but I'd check with @archishadatta about the status of the subpages.

<hr>

> The "Piping" page might be worth renaming to "Input and Output (I/O)" and this transitions nicely into "I/O Redirection". I also realized that we don't have a task that uses the "|" operator. Maybe we should create one on its own page and call it "Piping" instead. I think we are also missing usage/discussion about the "<" operator as well.

Good renaming suggestion, I'll make that change.
Oh yeah according to the content doc, there was supposed to be a task for ``|``. I'll take a look at that, see if we need to add one.
We're also missing ``>>`` and ``<<`` lol but I think we cut some operators because the lab was getting too long.

<hr>

> Another idea similar to this is to also provide a page where there's just a terminal for them to play with afterwards. Similar to PicoGym's web terminal. Probably leave a note on there somewhere that our terminal is very limited lol.

Cool idea, but I'm not sure we need a separate page for this since the user can just play with the terminal on any page.

**Review by zhangjuliet — APPROVED** [review]
LGTM!

**Pull request merged**
